FROM python:3.11-slim

# Set ENV vars
ENV PYTHONPATH=/app
# ensure pipx installs executables here:
ENV PATH="/root/.local/bin:${PATH}"


# Install OS build‑tools and pipx
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      make \
      curl && \
    rm -rf /var/lib/apt/lists/*

# Working directory
WORKDIR /app

# Copy the rest of the application
COPY app/ app/
COPY src/ src/
COPY pyproject.toml poetry.lock Makefile README.md ./

RUN pip install --upgrade pip

# Setup Poetry

RUN make setup_poetry ROOT="true"
RUN poetry config virtualenvs.create false 
RUN make install_dependecies_no_dev

# Expose FastAPI app port
EXPOSE 8080

# Run the FastAPI app (assumes it lives in mlops/app/app.py)
#CMD ["poetry", "run", "uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8080"]
